# Generated by Django 3.1.2 on 2020-10-17 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercreation',
            name='otp',
        ),
    ]
