# Generated by Django 3.1.2 on 2020-10-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_usercreation_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreation',
            name='otp',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AlterField(
            model_name='usercreation',
            name='email',
            field=models.EmailField(default='prprprprprprpr@mm.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='usercreation',
            name='name',
            field=models.CharField(default='...', max_length=100),
        ),
        migrations.AlterField(
            model_name='usercreation',
            name='password',
            field=models.CharField(default='sjsjjsjsjsjs', max_length=100),
        ),
        migrations.AlterField(
            model_name='usercreation',
            name='phone',
            field=models.CharField(default='...', max_length=15),
        ),
    ]
