# Generated by Django 3.1.2 on 2020-10-17 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20201017_1956'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetailsOfEvents',
            new_name='DetailsOfEvent',
        ),
    ]
