# Generated by Django 3.1.2 on 2020-10-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20201017_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreation',
            name='position',
            field=models.CharField(choices=[('Organise', 'organise'), ('Attend', 'Attend'), ('Sponsor', 'Sponsor')], default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
