# Generated by Django 3.1.2 on 2020-10-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_usercreation_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsofevent',
            name='description',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
